name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Create GCP Credentials File
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > credentials.json
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > ${{ github.workspace }}/credentials.json
        shell: bash


      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="google_application_credentials=${{ github.workspace }}/credentials.json" -input=false 

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="google_application_credentials=${{ github.workspace }}/credentials.json"
