name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Initialize Terraform
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Run Unit Tests
        run: bash tests/unit_test.sh

      - name: Run Integration Tests
        run: bash tests/integration_test.sh

      - name: Run Load Tests
        run: bash tests/load_test.sh

      - name: Run Security Tests
        run: bash tests/security_test.sh

      - name: Run Regression Tests
        run: bash tests/regression_test.sh

      - name: Run Performance Tests
        run: bash tests/performance_test.sh

      - name: Terraform Apply
        run: terraform apply tfplan
